name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4
      with:
        log-accepted-android-sdk-licenses: false
        packages: 'platforms;android-34 build-tools;34.0.0 platform-tools'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK with Gradle
      run: |
        ./gradlew assembleRelease

    - name: Upload APK Artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: release-apks
        path: app/build/outputs/apk/release/*.apk

  sign-and-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.release_tag != ''

    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-apks
          path: release-files

      - name: Upload APKs to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: release-files/*
          tag: ${{ inputs.release_tag }}
          file_glob: true
          prerelease: true
