name: Dependency review for pull requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
  
  dependency-review:
    runs-on: ubuntu-latest
    needs: dependency-submission
    if: github.event_name == 'pull_request'
    steps:
      - name: Perform dependency review
        uses: actions/dependency-review-action@v4
