name: Validate Fastlane metadata

on:
  workflow_dispatch:
  push:
      branches: [ "master" ]
  pull_request:
      branches: [ "master" ]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Fastlane Supply Metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2.0.0
